name: Synchronise Manual
on: 
  workflow_dispatch:
jobs:
  pull-hashes:
    runs-on: ubuntu-latest
    outputs:
      remote_commit: ${{ steps.remote_commit.outputs.remote_commit }}
      tracked_commit: ${{ steps.tracked_commit.outputs.tracked_commit }}
    steps:
      - name: Get Remote Commit
        id: remote_commit
        run: |
          REMOTE_COMMIT=$(curl https://api.github.com/repos/SteamDatabase/GameTracking-CS2/commits/master | jq ".sha" -r)
          printf "Remote SHA: $REMOTE_COMMIT"
          printf "remote_commit=$REMOTE_COMMIT\n" >> "$GITHUB_OUTPUT"
      - name: Get Tracked Commit
        id: tracked_commit
        run: |
          TRACKED_COMMIT_BASE64=$(curl https://api.github.com/repos/MolotovGG/CS2-Protobuf-Mirror/contents/hash.txt?ref=tracking | jq ".content" -r)
          if [[ TRACKED_COMMIT_BASE64 == "null" ]]; then
              printf "Tracked SHA: IS NULL? (${TRACKED_COMMIT_BASE64})"
              printf "tracked_commit=null\n" >> "$GITHUB_OUTPUT"
          else
              TRACKED_COMMIT=$(printf "${TRACKED_COMMIT_BASE64}" | base64 -d)
              printf "Tracked SHA: $TRACKED_COMMIT"
              printf "tracked_commit=$TRACKED_COMMIT\n" >> "$GITHUB_OUTPUT"
          fi
  update-main:
    runs-on: ubuntu-latest
    needs: [pull-hashes]
    if: "${{ (needs.update-tracking.outputs.protobuf-updated == '1') }}"
    env:
       latest_version: ${{ needs.pull-hashes.outputs.remote_commit }}
    permissions:
      contents: write
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.2.2
        with:
          path: 'main'
          ref: "main"
      - name: Checkout Tracking
        uses: actions/checkout@4.2.2
        with: 
          path: "tracking"
          ref: "tracking"
      - name: Copy Changes
        run: |
          rm -rf ./main/protobufs
          rm ./main/steam.inf
          rm ./main/hash.txt
          cp -r ./tracking/protobufs/ ./main/protobufs
          cp ./tracking/steam.inf ./main/steam.inf
          cp ./tracking/hash.txt ./main/hash.txt
          git checkout main
      - name: Create Commit
        run: |
            cp main
            git config user.email "bot@samh.dev"
            git config user.name "Synchronise"
            git add -A 
            git commit -m "Update Mirror to ${latest_version:0:12}"
            git push
      
  send-webhook:
    runs-on: ubuntu-latest
    needs: [update-main]
    env:
       latest_version: ${{ needs.pull-hashes.outputs.remote_commit }}
       webhook_path: ${{ secrets.WEBHOOK_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 3
      - name: send-webhook
        run: |
          DIFF="$(git --no-pager diff --stat HEAD~1 HEAD -- ./protobufs/)"
          THIS_COMMIT="$(git rev-parse HEAD)"
          TRACKED_HASH_SHORT="${latest_version:0:12}"
          CS_VERSION="$(cat steam.inf | grep 'PatchVersion=' | sed -Ee 's/.+=//g'^C)"
          REQ="{\"content\":null,\"embeds\":[{\"title\":\"Protobuf Mirror Update\",\"description\":\"```\n${DIFF}\n```\n[View on Github](https://github.com/MolotovGG/CS2-Protobuf-Mirror/commit/${THIS_COMMIT})\",\"color\":5831847,\"fields\":[{\"name\":\"Hash\",\"value\":\"${TRACKED_HASH_SHORT}\",\"inline\":true},{\"name\":\"CS2 Version\",\"value\":\"${CS_VERSION}\",\"inline\":true}],\"author\":{\"name\":\"MolotovGG/CS2-Protobuf-Mirror\",\"url\":\"https://github.com/MolotovGG/CS2-Protobuf-Mirror\",\"icon_url\":\"https://avatars.githubusercontent.com/in/15368\"}}],\"username\":\"Protobot\",\"avatar_url\":\"https://365randommuppets.wordpress.com/wp-content/uploads/2014/03/094-80s-robot.jpg?w=1200\",\"attachments\":[]}"
          URL="https://discord.com/api/webhooks/${webhook_path}?wait=true"
          curl -H "Content-Type: application/json" -d "$REQ" "$URL" -v
